### ISSUE TITLE
I/O system for spreadsheet databases

### ISSUE THREAD

**Issue by yicheng-w** [stuy-tetrabyte/graduation-req-tracker#6]
input/output system for spreadsheet databases

**Comment by elc1798** [comment]
Current backend of the database supports this feature and is ready for implementation by the frontend.

**Comment by elc1798** [comment]
5/25/16 - Began experimenting with ways to upload large files with Flask

**Comment by elc1798** [comment]
Completed ability to upload Excel spreadsheets. Will work on creating downloadable files for `student` and `courses` tables tomorrow
